### ISSUE TITLE
DruidJerseyClient Exception with spark 2.3 

### ISSUE THREAD

**Issue by legendtkl** [zapr-oss/druidry#90]
When I use druidry in spark streaming (version: 2.3.2) and I got the following error:

> 19/03/22 15:27:00 ERROR DruidJerseyClient: Exception while querying {}
in.zapr.druid.druidry.client.exception.QueryException
	at in.zapr.druid.druidry.client.DruidJerseyClient.handleInternalServerResponse(DruidJerseyClient.java:128)
	at in.zapr.druid.druidry.client.DruidJerseyClient.query(DruidJerseyClient.java:91)

Any help for this?

**Comment by legendtkl** [comment]
Hi, sorry for late reply.

I figured out the problem is jar conflict between DruidJerseyClient dependency and Spark lib jars.
