### ISSUE TITLE
this druid client conflicts with fastjson?

### ISSUE THREAD

**Issue by axzhcode** [zapr-oss/druidry#94]
when i import fastjson in pom, the response code is 500, remove is ok.
code: 
```java
public static void main(String[] args) {
        DateTime startTime = new DateTime(2016, 1, 1, 0,
                0, 0, DateTimeZone.UTC);
        DateTime endTime = new DateTime(2017, 1, 2, 0,
                0, 0, DateTimeZone.UTC);
        Interval interval = new Interval(startTime, endTime);
        PagingSpec pagingSpec = new PagingSpec(5, new HashMap<>());
        Granularity granularity = new SimpleGranularity(PredefinedGranularity.ALL);
        DruidSelectQuery query = DruidSelectQuery.builder()
                .dataSource("wikipedia")
                .descending(false)
                .granularity(granularity)
                .intervals(Collections.singletonList(interval))
                .pagingSpec(pagingSpec)
                .build();
        try {
            DruidConfiguration config = DruidConfiguration
                    .builder()
                    .host("localhost")
                    .port(8082)
                    .endpoint("druid/v2/")
                    .build();
            DruidClient client = new DruidJerseyClient(config);
            client.connect();
            String query1 = client.query(query);
            System.out.println(query1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

exception:
```
in.zapr.druid.druidry.client.exception.QueryException: null
	at in.zapr.druid.druidry.client.DruidJerseyClient.handleInternalServerResponse(DruidJerseyClient.java:145)
	at in.zapr.druid.druidry.client.DruidJerseyClient.query(DruidJerseyClient.java:108)
	at com.aaa.demo.springboot.DemoApplicationTests.main(DemoApplicationTests.java:50)
in.zapr.druid.druidry.client.exception.QueryException
	at in.zapr.druid.druidry.client.DruidJerseyClient.handleInternalServerResponse(DruidJerseyClient.java:145)
	at in.zapr.druid.druidry.client.DruidJerseyClient.query(DruidJerseyClient.java:108)
	at com.aaa.demo.springboot.DemoApplicationTests.main(DemoApplicationTests.java:50)
```

```
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.58</version>
        </dependency>
```

**Comment by axzhcode** [comment]
#89 this had a explain.
